# Variables nécessaires :
# - PROJECT_NAME
# - ORGANIZATION_NAME
# - EMAILS (Sous réserve. Array, on boucle dessus : owner + users)
# - ENV_LIST (doit venir de la base)
# - REPO_DEST
# - IS_INFRA

- name: Delete repo in project
  hosts: localhost
  vars:
    validation:
      type: object
      required: ["PROJECT_NAME", "ORGANIZATION_NAME", "ENV_LIST", "REPO_DEST"]
      properties:
        PROJECT_NAME:
          type: string
        ORGANIZATION_NAME:
          type: string
        ENV_LIST:
          type: array
          items:
            type: string
        REPO_DEST:
          type: string
      
  tasks:
    - name: Delete a repo in project
      ansible.builtin.debug:
        msg:
        - "Delete a repo in project"