- name: Provisionning DSO - Import git
  hosts: localhost
  vars:
    validation:
      required: ["PROJECT_NAME", "ORGANIZATION_NAME", "ENV_LIST", "REPO_DEST"]
      type: object
      properties:
        PROJECT_NAME:
          type: string
        ORGANIZATION_NAME:
          type: string
        ENV_LIST:
          type: array
          items:
            type: string
        REPO_DEST:
          type: array
          items:
            type: string
  tasks:
    - name: Delete a project
      ansible.builtin.debug:
        msg:
        - "Delete a project"